# Generated by Django 5.0.2 on 2024-04-19 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='im1',
            field=models.ImageField(blank=True, null=True, upload_to='hackathon/images/'),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='im2',
            field=models.ImageField(blank=True, null=True, upload_to='hackathon/images/'),
        ),
    ]
