# Generated by Django 5.0.2 on 2024-04-19 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_hackathon_im1_hackathon_im2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hackathon',
            old_name='im1',
            new_name='banner_image',
        ),
        migrations.RenameField(
            model_name='hackathon',
            old_name='im2',
            new_name='front_image',
        ),
    ]
