# Generated by Django 5.0.2 on 2024-04-30 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='first_place_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_place_hackathons', to='app.team'),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='second_place_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_place_hackathons', to='app.team'),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='third_place_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='third_place_hackathons', to='app.team'),
        ),
    ]
